apiVersion: v1
kind: Service
metadata:
  name: prom2teams
  namespace: monitoring
spec:
  selector:
    app: prom2teams
  type: NodePort
  ports:
   - port: 8089
    targetPort: 8089
    nodePort: 30092
