apiVersion: v1
kind: Service
metadata:
  name: comicbox-service
spec:
  selector:
    app: comicbox
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comicbox
  labels: 
   app: comicbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comicbox
  template:
    metadata:
      labels:
        app: comicbox
      annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: 'swagger-stats/metrics'
            prometheus.io/port: "3000"
    spec:
      containers:
        - name: comicbox
          image: evan21/swagger-test
          ports:
            - containerPort: 3000
